name: multifold_auth_microsoft
description: Implementation for Microsoft account authentication (MSA)
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  multifold_api: ^0.1.0
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  test: ^1.20.0

# See https://github.com/invertase/melos/issues/207
dependency_overrides:
  multifold_api:
    path: ../multifold_api
