name: multifold_api
description: MultiFold API package
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.8.0
  logger: ^1.1.0
  archive: ^3.1.8

dev_dependencies:
  flutter_lints: 1.0.4
