name: multifold_auth_mojang
description: Implementation for Mojang account at
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.20.0