name: multifold_auth_mojang
description: Implementation for Mojang account at
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  test: ^1.20.0
