name: multifold_app
description: MultiFold Minecraft launcher
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  multifold_core: ^0.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/