name: multifold_native
description: Native implementation of Multifold utilities
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0-124.0.dev <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
