name: multifold_core
description: MultiFold core implementation
version: 0.1.0
homepage: https://github.com/MultiFoldLauncher

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  multifold_api: ^0.1.0
  multifold_component_minecraft: ^0.1.0
  multifold_native: ^0.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  http: ^0.13.4
  logger: ^1.1.0

dev_dependencies:
  test: ^1.20.0
  flutter_lints: 1.0.4
